notifications:
  email: false
  slack:
    rooms:
      - secure: cPLdJj6RGVdnpLq85FMoYiluoUXLPUr9yF3MFN/hxGdMwC5f1kR8PoX8k7qewB5hJ9G0qf8TTANHhgymuMMjUKoiu6LxNcJIWs8vVMJMS5wbfAZO74xU9hPWJEheAy5EpVlyXwDbSD/9KRN/7MJE2ZMcaUABMEkIisROR7VIUy2+A4mTxKYo7uvHcjxpCmSNNEF55qq1LEy19xQfkbWLTL802bXSuJQp7qK05iF9t9B+5wpdmAOgM654vd9pBvsnZCgM+tIpJce5TmJxJnHYS2flrEm0vZwB4AuC+oiTQOaPjHMBwd5nigkyczm5AOWYl0RvXG1Ez/BRGbq0cZsx/oXUqmdy4T3Qmda6dXsz8SRfAqQ1MLA/0K1NMBhnOXlQ3pFc1D7rlOX+9+9kQyXVaBQusPBatozw1z/xBUmcKb/4RV8tH6OUa2AGU3+SZQfY0oH9pvBD5w0HAxVpsJzzDH02iR8+0V0+pbXRrpzVEYtB4jlonkly1W35Ni9q4Yv803Fq6CbaH5L2WHUladEKGbxROtVGgJ6xH0Ayy+ScE1cCzTfyg51oqsOVxzfwmBcLVigvUSIYCTDPat/ovUJ9eovtyHHQrs5naua+bsLM+2YdH/9C5frHJXfVa7yn6gayTK6L/GQVtvXQwnK74NXHknQVgHBUUDZOp3P5EQPGLO4=
    on_success: always
    on_failure: always
sudo: required
branches:
  only:
  - master
services:
- docker
script:
- docker build -t kostecki/batterymonitor web
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kostecki/batterymonitor
- curl -X POST -i $PORTAINER_WEBHOOK_URL