notifications:
  email: false
  slack:
    rooms:
      - secure: nMJkHrSpzfuLT79PnZlY/5REpic5PCku927EAulj7kYy830aWp/ndqXrgoeJED+g2e8Qlr4EBPa3mPioVPPRMWoU5mkujbUx9SHL/GU/hNdVAWfH6sIAm0C5Dn2THCe+CsYAyFGPKREH/pCyZ/fEBt0LITsAWVbTnqGfTZwyXpJ1Kp8tj8L96EfI6lUEGgCoAqAA5eQ6yzvK40bbznxFZXcNef38dqwAJfFi09VM0P6RrGZJS+YilqLaGvQ+X0MhvLuApjaLFkhYN6R8uGl00noj05UR1xWhazmKlfK4uRLKZCsWDCj2cScwAuVv3tzDXRc0CB45jOIEFs6Fcm85F3s7qciWfHUc1jxczhZggVcQ/r8D1AEW3FeQQu5jhX+PpFghiTp+6utVjKH0AUiOmFYgo1TONKBcNoaV4lyd1wmWC704y58v0/WCMZV8/BPMFRSjqSCYnR7MpYpOEq0PPjNQ1rtXHuxu4o9HEi6xeWeuNaD5bi/H4uiMeOQFosMhfT+5H1LLnLkOvAcMd7DwzwcfGA4NY4q3BLe0rMSXInv/mzER4fYeeRel3th38LRAK+rPCfloiCGe3T96n5fXfKK3LvEDFlumI+zaFpIAwBpoG7efa1mk8cvS1SfeqgjM4kk/y5uVBd8e1+uonXlOh4yqDURM5znV8S0Qyc0qRo4=
    on_success: always
sudo: required
branches:
  only:
  - master
services:
- docker
script:
- docker build -t kostecki/batterymonitor web
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kostecki/batterymonitor
- curl -X POST -i $PORTAINER_WEBHOOK_URL