notifications:
  email: false
  slack:
    rooms:
      - secure: TbfGQyHFmROCLqEjnSP0PrV0WyMRrEMuFKQFz1ZeonSZpj6smtgXZ8I8Iagwg10F1BHytAmbt5eqXIhiKqoj0euAyfPrg1I90BqmpnK5uWpX9yaGFKcW1asZzKP1bamJvX6fiE5oG2Kfz6W6C1QY4g0itCTk8ZauVaoDje3IDM4QLq16wmwrUnQeSpKc2qVolSdxr8FtY38SYzz2fClq8lb6386otHmaCLukOolquCCMG+uqu2b4YC9MTJ6jq7ZgwwhGiN1PhySpMw8W5qvOZ/BlckNCAItmsqWW+JagDy6YDm47dXsCOhuMGs+5dlVYAYOOVBT9tiWrUMQyKFJBGS/foGG7YJzKnRVuGPwmN2EXyl3iy5bUGfev97/o8zmqY7HL//lYsn9SsSIyf1BOEcqz1hNkm75yW7gOAua67iKyOMT3MAE+R6ofHkbSQtss2OFsoDf7XyAaEx2xR3bBBIYRlFfxhmhUVMMqQKjkfpqXb3hPXTmkn4wihy3MFx6aUcRsBuDZq/Qm576rx8ZCzCQkH9aK3eVtoQRsYoOvpLQA0mWRpatXaVaPKjbw+SNO9kBd5Szx1fnIIDB+fJ9HDCnr7D1fBK05ntYX+G8gm8SUu2hP9KRnRRtwczjblSuCsQO1spqee5nhs1VQwUw6KlYMf643ms9/ce66tVqrZ6Y=
sudo: required
branches:
  only:
  - master
services:
- docker
script:
- docker build --build-arg api_user=$REACT_APP_API_USER --build-arg api_pass=$REACT_APP_API_PASS
  -t kostecki/megapanel .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kostecki/megapanel
- curl -X POST -i $PORTAINER_WEBHOOK_URL